### ISSUE TITLE
Unique constraint failed - taggit_machinetags_machineslug

### ISSUE THREAD

**Issue by spassaro80** [lpomfrey/django-taggit-machinetags#4]
#Hello, regarding the issue #3 , I'v updated to version 0.9.0 but now it's giving me another error:

The first value is saved (with a ":" added as initial character like so):

Value posted in form: "Property:Value"
Value saved in model: ":Property:Value"

But if i try to input another value in form (i've tried with several combinations) it always raises a Unique Constraint error:

Unique constraint failed
taggit_machinetags_machineslug

Thank you in advance!

#

**Comment by lpomfrey** [comment]
It looks like the manager needs a bit of a rewrite to override the `_to_tag_model_instances` method here: https://github.com/jazzband/django-taggit/blob/bd342abb77b0ec3135250de56e7985555d649379/taggit/managers.py#L192
instead of completely overriding `add` and so on. I suspect this actual issue is that the form is calling `set()` instead of `add()` (which we don't override but relies on that method).

I'm quite busy at the moment, but I'll try and have a look this week sometime. Unless you feel like putting a pull request together.

**Comment by lpomfrey** [comment]
This is hopefully fixed in 1.0.0.
